/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.nbk.demo.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8741916462834086223L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"org.nbk.demo.kafka.avro.model\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"productType\",\"type\":\"string\"},{\"name\":\"productDescription\",\"type\":\"string\"},{\"name\":\"productShortDesc\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<Product>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence productId;
   private java.lang.CharSequence productName;
   private java.lang.CharSequence productType;
   private java.lang.CharSequence productDescription;
   private java.lang.CharSequence productShortDesc;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Product() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param productName The new value for productName
   * @param productType The new value for productType
   * @param productDescription The new value for productDescription
   * @param productShortDesc The new value for productShortDesc
   */
  public Product(java.lang.CharSequence productId, java.lang.CharSequence productName, java.lang.CharSequence productType, java.lang.CharSequence productDescription, java.lang.CharSequence productShortDesc) {
    this.productId = productId;
    this.productName = productName;
    this.productType = productType;
    this.productDescription = productDescription;
    this.productShortDesc = productShortDesc;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return productName;
    case 2: return productType;
    case 3: return productDescription;
    case 4: return productShortDesc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.CharSequence)value$; break;
    case 1: productName = (java.lang.CharSequence)value$; break;
    case 2: productType = (java.lang.CharSequence)value$; break;
    case 3: productDescription = (java.lang.CharSequence)value$; break;
    case 4: productShortDesc = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'productType' field.
   * @return The value of the 'productType' field.
   */
  public java.lang.CharSequence getProductType() {
    return productType;
  }


  /**
   * Sets the value of the 'productType' field.
   * @param value the value to set.
   */
  public void setProductType(java.lang.CharSequence value) {
    this.productType = value;
  }

  /**
   * Gets the value of the 'productDescription' field.
   * @return The value of the 'productDescription' field.
   */
  public java.lang.CharSequence getProductDescription() {
    return productDescription;
  }


  /**
   * Sets the value of the 'productDescription' field.
   * @param value the value to set.
   */
  public void setProductDescription(java.lang.CharSequence value) {
    this.productDescription = value;
  }

  /**
   * Gets the value of the 'productShortDesc' field.
   * @return The value of the 'productShortDesc' field.
   */
  public java.lang.CharSequence getProductShortDesc() {
    return productShortDesc;
  }


  /**
   * Sets the value of the 'productShortDesc' field.
   * @param value the value to set.
   */
  public void setProductShortDesc(java.lang.CharSequence value) {
    this.productShortDesc = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   * @return A new Product RecordBuilder
   */
  public static org.nbk.demo.kafka.avro.model.Product.Builder newBuilder() {
    return new org.nbk.demo.kafka.avro.model.Product.Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static org.nbk.demo.kafka.avro.model.Product.Builder newBuilder(org.nbk.demo.kafka.avro.model.Product.Builder other) {
    if (other == null) {
      return new org.nbk.demo.kafka.avro.model.Product.Builder();
    } else {
      return new org.nbk.demo.kafka.avro.model.Product.Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static org.nbk.demo.kafka.avro.model.Product.Builder newBuilder(org.nbk.demo.kafka.avro.model.Product other) {
    if (other == null) {
      return new org.nbk.demo.kafka.avro.model.Product.Builder();
    } else {
      return new org.nbk.demo.kafka.avro.model.Product.Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    private java.lang.CharSequence productId;
    private java.lang.CharSequence productName;
    private java.lang.CharSequence productType;
    private java.lang.CharSequence productDescription;
    private java.lang.CharSequence productShortDesc;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.nbk.demo.kafka.avro.model.Product.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productType)) {
        this.productType = data().deepCopy(fields()[2].schema(), other.productType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.productShortDesc)) {
        this.productShortDesc = data().deepCopy(fields()[4].schema(), other.productShortDesc);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     * @param other The existing instance to copy.
     */
    private Builder(org.nbk.demo.kafka.avro.model.Product other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productType)) {
        this.productType = data().deepCopy(fields()[2].schema(), other.productType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.productShortDesc)) {
        this.productShortDesc = data().deepCopy(fields()[4].schema(), other.productShortDesc);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.productName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productType' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductType() {
      return productType;
    }


    /**
      * Sets the value of the 'productType' field.
      * @param value The value of 'productType'.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder setProductType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.productType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productType' field has been set.
      * @return True if the 'productType' field has been set, false otherwise.
      */
    public boolean hasProductType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productType' field.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder clearProductType() {
      productType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductDescription() {
      return productDescription;
    }


    /**
      * Sets the value of the 'productDescription' field.
      * @param value The value of 'productDescription'.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder setProductDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.productDescription = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productDescription' field has been set.
      * @return True if the 'productDescription' field has been set, false otherwise.
      */
    public boolean hasProductDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productDescription' field.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder clearProductDescription() {
      productDescription = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'productShortDesc' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductShortDesc() {
      return productShortDesc;
    }


    /**
      * Sets the value of the 'productShortDesc' field.
      * @param value The value of 'productShortDesc'.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder setProductShortDesc(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.productShortDesc = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'productShortDesc' field has been set.
      * @return True if the 'productShortDesc' field has been set, false otherwise.
      */
    public boolean hasProductShortDesc() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'productShortDesc' field.
      * @return This builder.
      */
    public org.nbk.demo.kafka.avro.model.Product.Builder clearProductShortDesc() {
      productShortDesc = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        Product record = new Product();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productName = fieldSetFlags()[1] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.productType = fieldSetFlags()[2] ? this.productType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.productDescription = fieldSetFlags()[3] ? this.productDescription : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.productShortDesc = fieldSetFlags()[4] ? this.productShortDesc : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product>
    WRITER$ = (org.apache.avro.io.DatumWriter<Product>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product>
    READER$ = (org.apache.avro.io.DatumReader<Product>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.productId);

    out.writeString(this.productName);

    out.writeString(this.productType);

    out.writeString(this.productDescription);

    out.writeString(this.productShortDesc);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);

      this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);

      this.productType = in.readString(this.productType instanceof Utf8 ? (Utf8)this.productType : null);

      this.productDescription = in.readString(this.productDescription instanceof Utf8 ? (Utf8)this.productDescription : null);

      this.productShortDesc = in.readString(this.productShortDesc instanceof Utf8 ? (Utf8)this.productShortDesc : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);
          break;

        case 1:
          this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);
          break;

        case 2:
          this.productType = in.readString(this.productType instanceof Utf8 ? (Utf8)this.productType : null);
          break;

        case 3:
          this.productDescription = in.readString(this.productDescription instanceof Utf8 ? (Utf8)this.productDescription : null);
          break;

        case 4:
          this.productShortDesc = in.readString(this.productShortDesc instanceof Utf8 ? (Utf8)this.productShortDesc : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










